name: Packer Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  image:
    name: Build image
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-2
          role-to-assume: arn:aws:iam::654897662046:role/github-actions/plural-sysbox-amis-packer
          role-session-name: SysboxAmisPacker
      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: 1.9.2
      - name: Get files
        run: make get-files
      - name: Run `packer init`
        id: init
        run: "packer init ."
      - name: Run `packer validate`
        id: validate
        run: "packer validate ."
      - name: Run `packer build`
        id: build
        run: "packer build ."
  # trivy-scan:
  #   name: Trivy fs scan
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: read # for actions/checkout to fetch code
  #     security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
  #     actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3
  #     - name: Run Trivy vulnerability scanner in fs mode
  #       uses: aquasecurity/trivy-action@master
  #       with:
  #         scan-type: 'fs'
  #         hide-progress: false
  #         format: 'sarif'
  #         output: 'trivy-results.sarif'
  #         scanners: 'vuln,secret'
  #         ignore-unfixed: true
  #         #severity: 'CRITICAL,HIGH'
  #     - name: Upload Trivy scan results to GitHub Security tab
  #       uses: github/codeql-action/upload-sarif@v2
  #       with:
  #         sarif_file: 'trivy-results.sarif'
